/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oshopping;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class StoreDetails_sub extends javax.swing.JFrame {

    /**
     * Creates new form StoreDetails_sub
     */
    public StoreDetails_sub() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        B11 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        B3 = new javax.swing.JRadioButton();
        B4 = new javax.swing.JRadioButton();
        B5 = new javax.swing.JRadioButton();
        B6 = new javax.swing.JRadioButton();
        B7 = new javax.swing.JRadioButton();
        B8 = new javax.swing.JRadioButton();
        B1 = new javax.swing.JRadioButton();
        B9 = new javax.swing.JRadioButton();
        B2 = new javax.swing.JRadioButton();
        B10 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        A1 = new javax.swing.JRadioButton();
        A2 = new javax.swing.JRadioButton();
        A3 = new javax.swing.JRadioButton();
        A4 = new javax.swing.JRadioButton();
        A5 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Location_id", "City_name"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 200, 108));

        jButton1.setBackground(new java.awt.Color(153, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Show Table");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 370, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Store_id", "Store_name"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 200, 110));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "sr_id", "s_name", "s_age", "s_phn", "monthly_income"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 380, 252));

        jInternalFrame1.setVisible(true);

        buttonGroup1.add(B11);
        B11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        B11.setText("Gazipur");

        jButton2.setBackground(new java.awt.Color(0, 255, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(B3);
        B3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        B3.setText("Rajshahi");

        buttonGroup1.add(B4);
        B4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        B4.setText("Khulna");

        buttonGroup1.add(B5);
        B5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        B5.setText("Sylhet");

        buttonGroup1.add(B6);
        B6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        B6.setText("Mymensingh");

        buttonGroup1.add(B7);
        B7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        B7.setText("Barisal");

        buttonGroup1.add(B8);
        B8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        B8.setText("Rangpur");

        buttonGroup1.add(B1);
        B1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        B1.setText("Dhaka");

        buttonGroup1.add(B9);
        B9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        B9.setText("Comilla");

        buttonGroup1.add(B2);
        B2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        B2.setText("Chittagong");

        buttonGroup1.add(B10);
        B10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        B10.setText("Narayanganj");

        jLabel1.setBackground(new java.awt.Color(51, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FILTER PAGE");

        jLabel2.setBackground(new java.awt.Color(0, 255, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Choose City");

        buttonGroup2.add(A1);
        A1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        A1.setText("<= 20");

        buttonGroup2.add(A2);
        A2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        A2.setText(" <= 30   &&   >= 21");

        buttonGroup2.add(A3);
        A3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        A3.setText(" <= 40   &&   >= 31");

        buttonGroup2.add(A4);
        A4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        A4.setText(" <= 50  &&   >= 41");

        buttonGroup2.add(A5);
        A5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        A5.setText(" >=51");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("AGE");

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("SEARCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setText("Our Primium Seller");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 102, 102));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("Our Best Seller");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 153, 153));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setText("Target For Seller");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(B8))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(B9))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(B10))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(B11))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton2))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B1)
                            .addComponent(B2)
                            .addComponent(B3)
                            .addComponent(B4)
                            .addComponent(B5)
                            .addComponent(B6)
                            .addComponent(jLabel2)
                            .addComponent(B7))
                        .addGap(43, 43, 43)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(A1)
                            .addComponent(A2)
                            .addComponent(A3)
                            .addComponent(A4)
                            .addComponent(A5)
                            .addComponent(jButton4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(B1)
                        .addGap(0, 0, 0)
                        .addComponent(B2)
                        .addGap(0, 0, 0)
                        .addComponent(B3)
                        .addGap(0, 0, 0)
                        .addComponent(B4)
                        .addGap(0, 0, 0)
                        .addComponent(B5)
                        .addGap(0, 0, 0)
                        .addComponent(B6)
                        .addGap(0, 0, 0)
                        .addComponent(B7)
                        .addGap(0, 0, 0)
                        .addComponent(B8)
                        .addGap(0, 0, 0)
                        .addComponent(B9)
                        .addGap(0, 0, 0)
                        .addComponent(B10)
                        .addGap(0, 0, 0)
                        .addComponent(B11)
                        .addGap(2, 2, 2)
                        .addComponent(jButton2))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(A1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 352, 470));

        jButton3.setBackground(new java.awt.Color(153, 255, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 200, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("SELLER TABLE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("STORE TABLE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("LOCATION LABLE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        jButton5.setBackground(new java.awt.Color(153, 255, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("CLEAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 200, -1));

        jButton6.setBackground(new java.awt.Color(153, 255, 204));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("CLEAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 370, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("STORE DETAILS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, 50));

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -290, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Documents\\NetBeansProjects\\OShopping\\src\\oshopping\\images\\AdvancedFilthyKoala-max-1mb.gif")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -380, -1, -1));

        jButton10.setBackground(new java.awt.Color(102, 255, 204));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setText("BACK");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
                  try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query1 ="SELECT * FROM LOCATIONS;";
            ResultSet rs=  st.executeQuery(query1);
          
            while(rs.next()){
               String lid = String.valueOf(rs.getInt("LOCATION_ID"));
               String lname = String.valueOf(rs.getString("CITY"));
               String tbData[] = {lid,lname};
               DefaultTableModel model = (DefaultTableModel)jTable1.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
                  try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query1 ="SELECT * FROM STORE;";
            ResultSet rs=  st.executeQuery(query1);
          
            while(rs.next()){
               String lid = String.valueOf(rs.getInt("STORE_ID"));
               String lname = String.valueOf(rs.getString("STORE_NAME"));
               String tbData[] = {lid,lname};
               DefaultTableModel model = (DefaultTableModel)jTable2.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
                  try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query2 ="SELECT * FROM SELLER;";
            ResultSet rs2 =  st.executeQuery(query2);
          
            while(rs2.next()){
               String id = String.valueOf(rs2.getInt("SELLER_ID"));
               String name = String.valueOf(rs2.getString("SELLER_NAME"));
               String age = String.valueOf(rs2.getInt("AGE"));
               String num = String.valueOf(rs2.getString("PHONE_NUMBER"));
               String payment = String.valueOf(rs2.getInt("PAYMENT_PER_YEAR"));
               String tbData[] = {id,name,age,num,payment};
               DefaultTableModel model = (DefaultTableModel)jTable3.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(B1.isSelected()== true)
        {
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query2 ="SELECT\n" +
"*\n" +
"FROM\n" +
"SELLER\n" +
"WHERE\n" +
"STORE_ID IN (SELECT\n" +
"STORE_ID\n" +
"FROM\n" +
"STORE\n" +
"WHERE\n" +
"LOCATION_ID IN (SELECT\n" +
"LOCATION_ID\n" +
"FROM\n" +
"LOCATIONS\n" +
"WHERE\n" +
"CITY= 'Dhaka'))\n" +
"ORDER BY SELLER_ID;";
            ResultSet rs2 =  st.executeQuery(query2);
          
            while(rs2.next()){
               String id = String.valueOf(rs2.getInt("SELLER_ID"));
               String name = String.valueOf(rs2.getString("SELLER_NAME"));
               String age = String.valueOf(rs2.getInt("AGE"));
               String num = String.valueOf(rs2.getString("PHONE_NUMBER"));
               String payment = String.valueOf(rs2.getInt("PAYMENT_PER_YEAR"));
               String tbData[] = {id,name,age,num,payment};
               DefaultTableModel model = (DefaultTableModel)jTable3.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
        }
        
        else if(B2.isSelected()== true)
        {
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query2 ="SELECT\n" +
"*\n" +
"FROM\n" +
"SELLER\n" +
"WHERE\n" +
"STORE_ID IN (SELECT\n" +
"STORE_ID\n" +
"FROM\n" +
"STORE\n" +
"WHERE\n" +
"LOCATION_ID IN (SELECT\n" +
"LOCATION_ID\n" +
"FROM\n" +
"LOCATIONS\n" +
"WHERE\n" +
"CITY= 'Chittagong'))\n" +
"ORDER BY SELLER_ID;";
            ResultSet rs2 =  st.executeQuery(query2);
          
            while(rs2.next()){
               String id = String.valueOf(rs2.getInt("SELLER_ID"));
               String name = String.valueOf(rs2.getString("SELLER_NAME"));
               String age = String.valueOf(rs2.getInt("AGE"));
               String num = String.valueOf(rs2.getString("PHONE_NUMBER"));
               String payment = String.valueOf(rs2.getInt("PAYMENT_PER_YEAR"));
               String tbData[] = {id,name,age,num,payment};
               DefaultTableModel model = (DefaultTableModel)jTable3.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
        }
         
         else if(B3.isSelected()== true)
        {
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query2 ="SELECT\n" +
"*\n" +
"FROM\n" +
"SELLER\n" +
"WHERE\n" +
"STORE_ID IN (SELECT\n" +
"STORE_ID\n" +
"FROM\n" +
"STORE\n" +
"WHERE\n" +
"LOCATION_ID IN (SELECT\n" +
"LOCATION_ID\n" +
"FROM\n" +
"LOCATIONS\n" +
"WHERE\n" +
"CITY= 'Rajshahi'))\n" +
"ORDER BY SELLER_ID;";
            ResultSet rs2 =  st.executeQuery(query2);
          
            while(rs2.next()){
               String id = String.valueOf(rs2.getInt("SELLER_ID"));
               String name = String.valueOf(rs2.getString("SELLER_NAME"));
               String age = String.valueOf(rs2.getInt("AGE"));
               String num = String.valueOf(rs2.getString("PHONE_NUMBER"));
               String payment = String.valueOf(rs2.getInt("PAYMENT_PER_YEAR"));
               String tbData[] = {id,name,age,num,payment};
               DefaultTableModel model = (DefaultTableModel)jTable3.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
        }
          
          
          else if(B4.isSelected()== true)
        {
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query2 ="SELECT\n" +
"*\n" +
"FROM\n" +
"SELLER\n" +
"WHERE\n" +
"STORE_ID IN (SELECT\n" +
"STORE_ID\n" +
"FROM\n" +
"STORE\n" +
"WHERE\n" +
"LOCATION_ID IN (SELECT\n" +
"LOCATION_ID\n" +
"FROM\n" +
"LOCATIONS\n" +
"WHERE\n" +
"CITY= 'Khulna'))\n" +
"ORDER BY SELLER_ID;";
            ResultSet rs2 =  st.executeQuery(query2);
          
            while(rs2.next()){
               String id = String.valueOf(rs2.getInt("SELLER_ID"));
               String name = String.valueOf(rs2.getString("SELLER_NAME"));
               String age = String.valueOf(rs2.getInt("AGE"));
               String num = String.valueOf(rs2.getString("PHONE_NUMBER"));
               String payment = String.valueOf(rs2.getInt("PAYMENT_PER_YEAR"));
               String tbData[] = {id,name,age,num,payment};
               DefaultTableModel model = (DefaultTableModel)jTable3.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
        }
           
           
           
           
           else if(B5.isSelected()== true)
        {
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query2 ="SELECT\n" +
"*\n" +
"FROM\n" +
"SELLER\n" +
"WHERE\n" +
"STORE_ID IN (SELECT\n" +
"STORE_ID\n" +
"FROM\n" +
"STORE\n" +
"WHERE\n" +
"LOCATION_ID IN (SELECT\n" +
"LOCATION_ID\n" +
"FROM\n" +
"LOCATIONS\n" +
"WHERE\n" +
"CITY= 'Sylhet'))\n" +
"ORDER BY SELLER_ID;";
            ResultSet rs2 =  st.executeQuery(query2);
          
            while(rs2.next()){
               String id = String.valueOf(rs2.getInt("SELLER_ID"));
               String name = String.valueOf(rs2.getString("SELLER_NAME"));
               String age = String.valueOf(rs2.getInt("AGE"));
               String num = String.valueOf(rs2.getString("PHONE_NUMBER"));
               String payment = String.valueOf(rs2.getInt("PAYMENT_PER_YEAR"));
               String tbData[] = {id,name,age,num,payment};
               DefaultTableModel model = (DefaultTableModel)jTable3.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
        }
            
            
            
            else if(B6.isSelected()== true)
        {
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query2 ="SELECT\n" +
"*\n" +
"FROM\n" +
"SELLER\n" +
"WHERE\n" +
"STORE_ID IN (SELECT\n" +
"STORE_ID\n" +
"FROM\n" +
"STORE\n" +
"WHERE\n" +
"LOCATION_ID IN (SELECT\n" +
"LOCATION_ID\n" +
"FROM\n" +
"LOCATIONS\n" +
"WHERE\n" +
"CITY= 'Mymensingh'))\n" +
"ORDER BY SELLER_ID;";
            ResultSet rs2 =  st.executeQuery(query2);
          
            while(rs2.next()){
               String id = String.valueOf(rs2.getInt("SELLER_ID"));
               String name = String.valueOf(rs2.getString("SELLER_NAME"));
               String age = String.valueOf(rs2.getInt("AGE"));
               String num = String.valueOf(rs2.getString("PHONE_NUMBER"));
               String payment = String.valueOf(rs2.getInt("PAYMENT_PER_YEAR"));
               String tbData[] = {id,name,age,num,payment};
               DefaultTableModel model = (DefaultTableModel)jTable3.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
        }
             
             
            else if(B7.isSelected()== true)
        {
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query2 ="SELECT\n" +
"*\n" +
"FROM\n" +
"SELLER\n" +
"WHERE\n" +
"STORE_ID IN (SELECT\n" +
"STORE_ID\n" +
"FROM\n" +
"STORE\n" +
"WHERE\n" +
"LOCATION_ID IN (SELECT\n" +
"LOCATION_ID\n" +
"FROM\n" +
"LOCATIONS\n" +
"WHERE\n" +
"CITY= 'Barisal'))\n" +
"ORDER BY SELLER_ID;";
            ResultSet rs2 =  st.executeQuery(query2);
          
            while(rs2.next()){
               String id = String.valueOf(rs2.getInt("SELLER_ID"));
               String name = String.valueOf(rs2.getString("SELLER_NAME"));
               String age = String.valueOf(rs2.getInt("AGE"));
               String num = String.valueOf(rs2.getString("PHONE_NUMBER"));
               String payment = String.valueOf(rs2.getInt("PAYMENT_PER_YEAR"));
               String tbData[] = {id,name,age,num,payment};
               DefaultTableModel model = (DefaultTableModel)jTable3.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
        }
              
              
             else if(B8.isSelected()== true)
        {
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query2 ="SELECT\n" +
"*\n" +
"FROM\n" +
"SELLER\n" +
"WHERE\n" +
"STORE_ID IN (SELECT\n" +
"STORE_ID\n" +
"FROM\n" +
"STORE\n" +
"WHERE\n" +
"LOCATION_ID IN (SELECT\n" +
"LOCATION_ID\n" +
"FROM\n" +
"LOCATIONS\n" +
"WHERE\n" +
"CITY= 'Rangpur'))\n" +
"ORDER BY SELLER_ID;";
            ResultSet rs2 =  st.executeQuery(query2);
          
            while(rs2.next()){
               String id = String.valueOf(rs2.getInt("SELLER_ID"));
               String name = String.valueOf(rs2.getString("SELLER_NAME"));
               String age = String.valueOf(rs2.getInt("AGE"));
               String num = String.valueOf(rs2.getString("PHONE_NUMBER"));
               String payment = String.valueOf(rs2.getInt("PAYMENT_PER_YEAR"));
               String tbData[] = {id,name,age,num,payment};
               DefaultTableModel model = (DefaultTableModel)jTable3.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
        }
               
               
               else if(B9.isSelected()== true)
        {
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query2 ="SELECT\n" +
"*\n" +
"FROM\n" +
"SELLER\n" +
"WHERE\n" +
"STORE_ID IN (SELECT\n" +
"STORE_ID\n" +
"FROM\n" +
"STORE\n" +
"WHERE\n" +
"LOCATION_ID IN (SELECT\n" +
"LOCATION_ID\n" +
"FROM\n" +
"LOCATIONS\n" +
"WHERE\n" +
"CITY= 'Comilla'))\n" +
"ORDER BY SELLER_ID;";
            ResultSet rs2 =  st.executeQuery(query2);
          
            while(rs2.next()){
               String id = String.valueOf(rs2.getInt("SELLER_ID"));
               String name = String.valueOf(rs2.getString("SELLER_NAME"));
               String age = String.valueOf(rs2.getInt("AGE"));
               String num = String.valueOf(rs2.getString("PHONE_NUMBER"));
               String payment = String.valueOf(rs2.getInt("PAYMENT_PER_YEAR"));
               String tbData[] = {id,name,age,num,payment};
               DefaultTableModel model = (DefaultTableModel)jTable3.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
        }
                
                
                else if(B10.isSelected()== true)
        {
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query2 ="SELECT\n" +
"*\n" +
"FROM\n" +
"SELLER\n" +
"WHERE\n" +
"STORE_ID IN (SELECT\n" +
"STORE_ID\n" +
"FROM\n" +
"STORE\n" +
"WHERE\n" +
"LOCATION_ID IN (SELECT\n" +
"LOCATION_ID\n" +
"FROM\n" +
"LOCATIONS\n" +
"WHERE\n" +
"CITY= 'Narayanganj'))\n" +
"ORDER BY SELLER_ID;";
            ResultSet rs2 =  st.executeQuery(query2);
          
            while(rs2.next()){
               String id = String.valueOf(rs2.getInt("SELLER_ID"));
               String name = String.valueOf(rs2.getString("SELLER_NAME"));
               String age = String.valueOf(rs2.getInt("AGE"));
               String num = String.valueOf(rs2.getString("PHONE_NUMBER"));
               String payment = String.valueOf(rs2.getInt("PAYMENT_PER_YEAR"));
               String tbData[] = {id,name,age,num,payment};
               DefaultTableModel model = (DefaultTableModel)jTable3.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
        }
                 
                 
                 else if(B11.isSelected()== true)
        {
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query2 ="SELECT\n" +
"*\n" +
"FROM\n" +
"SELLER\n" +
"WHERE\n" +
"STORE_ID IN (SELECT\n" +
"STORE_ID\n" +
"FROM\n" +
"STORE\n" +
"WHERE\n" +
"LOCATION_ID IN (SELECT\n" +
"LOCATION_ID\n" +
"FROM\n" +
"LOCATIONS\n" +
"WHERE\n" +
"CITY= 'Gazipur'))\n" +
"ORDER BY SELLER_ID;";
            ResultSet rs2 =  st.executeQuery(query2);
          
            while(rs2.next()){
               String id = String.valueOf(rs2.getInt("SELLER_ID"));
               String name = String.valueOf(rs2.getString("SELLER_NAME"));
               String age = String.valueOf(rs2.getInt("AGE"));
               String num = String.valueOf(rs2.getString("PHONE_NUMBER"));
               String payment = String.valueOf(rs2.getInt("PAYMENT_PER_YEAR"));
               String tbData[] = {id,name,age,num,payment};
               DefaultTableModel model = (DefaultTableModel)jTable3.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
        }
                  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         jTable2.setModel(new DefaultTableModel(null,new String[]{"STORE_ID","STORE_NAME"}));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
if(A1.isSelected()== true){
     try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query1 ="SELECT\n" +
"STORE_ID,STORE_NAME\n" +
"FROM\n" +
"STORE s\n" +
"WHERE\n" +
"EXISTS( SELECT\n" +
"*\n" +
"FROM\n" +
"SELLER e\n" +
"WHERE\n" +
"AGE <= 20 AND AGE >= 0\n" +
"AND e.STORE_ID = s.STORE_ID)\n" +
"ORDER BY STORE_ID DESC";
            ResultSet rs=  st.executeQuery(query1);
          
            while(rs.next()){
               String lid = String.valueOf(rs.getInt("STORE_ID"));
               String lname = String.valueOf(rs.getString("STORE_NAME"));
               String tbData[] = {lid,lname};
               DefaultTableModel model = (DefaultTableModel)jTable2.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
}
else if(A2.isSelected()== true){
     try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query1 ="SELECT\n" +
"STORE_ID,STORE_NAME\n" +
"FROM\n" +
"STORE s\n" +
"WHERE\n" +
"EXISTS( SELECT\n" +
"*\n" +
"FROM\n" +
"SELLER e\n" +
"WHERE\n" +
"AGE <= 30 AND AGE >= 21\n" +
"AND e.STORE_ID = s.STORE_ID)\n" +
"ORDER BY STORE_ID DESC";
            ResultSet rs=  st.executeQuery(query1);
          
            while(rs.next()){
               String lid = String.valueOf(rs.getInt("STORE_ID"));
               String lname = String.valueOf(rs.getString("STORE_NAME"));
               String tbData[] = {lid,lname};
               DefaultTableModel model = (DefaultTableModel)jTable2.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
}
else if(A3.isSelected()== true){
     try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query1 ="SELECT\n" +
"STORE_ID,STORE_NAME\n" +
"FROM\n" +
"STORE s\n" +
"WHERE\n" +
"EXISTS( SELECT\n" +
"*\n" +
"FROM\n" +
"SELLER e\n" +
"WHERE\n" +
"AGE <= 40 AND AGE >= 31\n" +
"AND e.STORE_ID = s.STORE_ID)\n" +
"ORDER BY STORE_ID DESC";
            ResultSet rs=  st.executeQuery(query1);
          
            while(rs.next()){
               String lid = String.valueOf(rs.getInt("STORE_ID"));
               String lname = String.valueOf(rs.getString("STORE_NAME"));
               String tbData[] = {lid,lname};
               DefaultTableModel model = (DefaultTableModel)jTable2.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
}
else if(A4.isSelected()== true){
     try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query1 ="SELECT\n" +
"STORE_ID,STORE_NAME\n" +
"FROM\n" +
"STORE s\n" +
"WHERE\n" +
"EXISTS( SELECT\n" +
"*\n" +
"FROM\n" +
"SELLER e\n" +
"WHERE\n" +
"AGE <= 50 AND AGE >= 41\n" +
"AND e.STORE_ID = s.STORE_ID)\n" +
"ORDER BY STORE_ID DESC";
            ResultSet rs=  st.executeQuery(query1);
          
            while(rs.next()){
               String lid = String.valueOf(rs.getInt("STORE_ID"));
               String lname = String.valueOf(rs.getString("STORE_NAME"));
               String tbData[] = {lid,lname};
               DefaultTableModel model = (DefaultTableModel)jTable2.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
}
else if(A5.isSelected()== true){
     try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query1 ="SELECT\n" +
"STORE_ID,STORE_NAME\n" +
"FROM\n" +
"STORE s\n" +
"WHERE\n" +
"EXISTS( SELECT\n" +
"*\n" +
"FROM\n" +
"SELLER e\n" +
"WHERE\n" +
"AGE >= 51\n" +
"AND e.STORE_ID = s.STORE_ID)\n" +
"ORDER BY STORE_ID DESC";
            ResultSet rs=  st.executeQuery(query1);
          
            while(rs.next()){
               String lid = String.valueOf(rs.getInt("STORE_ID"));
               String lname = String.valueOf(rs.getString("STORE_NAME"));
               String tbData[] = {lid,lname};
               DefaultTableModel model = (DefaultTableModel)jTable2.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         jTable1.setModel(new DefaultTableModel(null,new String[]{"LOCATION_ID","LOCATION_NAME"}));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jTable3.setModel(new DefaultTableModel(null,new String[]{"SELLER_ID","SELLER_NAME","AGE","PHONE_NUMBER","PAYMENT_PER_YEAR"}));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query2 ="SELECT\n" +
"*\n" +
"FROM\n" +
"SELLER\n" +
"WHERE\n" +
"PAYMENT_PER_YEAR >= ALL (SELECT\n" +
"PAYMENT_PER_YEAR\n" +
"FROM\n" +
"SELLER\n" +
"WHERE\n" +
" PAYMENT_PER_YEAR > 10000)";
            ResultSet rs2 =  st.executeQuery(query2);
          
            while(rs2.next()){
               String id = String.valueOf(rs2.getInt("SELLER_ID"));
               String name = String.valueOf(rs2.getString("SELLER_NAME"));
               String age = String.valueOf(rs2.getInt("AGE"));
               String num = String.valueOf(rs2.getString("PHONE_NUMBER"));
               String payment = String.valueOf(rs2.getInt("PAYMENT_PER_YEAR"));
               String tbData[] = {id,name,age,num,payment};
               DefaultTableModel model = (DefaultTableModel)jTable3.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
               try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query2 ="SELECT\n" +
"*\n" +
"FROM\n" +
"SELLER\n" +
"WHERE\n" +
"PAYMENT_PER_YEAR >= ANY (SELECT\n" +
"PAYMENT_PER_YEAR\n" +
"FROM\n" +
"SELLER\n" +
"WHERE\n" +
" PAYMENT_PER_YEAR > 10000)";
            ResultSet rs2 =  st.executeQuery(query2);
          
            while(rs2.next()){
               String id = String.valueOf(rs2.getInt("SELLER_ID"));
               String name = String.valueOf(rs2.getString("SELLER_NAME"));
               String age = String.valueOf(rs2.getInt("AGE"));
               String num = String.valueOf(rs2.getString("PHONE_NUMBER"));
               String payment = String.valueOf(rs2.getInt("PAYMENT_PER_YEAR"));
               String tbData[] = {id,name,age,num,payment};
               DefaultTableModel model = (DefaultTableModel)jTable3.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }  
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
                       try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=EShopping;user=sa;password=123456 ";
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String query2 ="SELECT\n" +
"SELLER_ID,\n" +
"SELLER_NAME,\n" +
"AGE,\n" +
"PHONE_NUMBER,\n" +
"PAYMENT_PER_YEAR-\n" +
"(SELECT\n" +
"ROUND(AVG(PAYMENT_PER_YEAR), 0)\n" +
"FROM\n" +
"SELLER) difference\n" +
"FROM\n" +
"SELLER  ; ";
            ResultSet rs2 =  st.executeQuery(query2);
          
            while(rs2.next()){
               String id = String.valueOf(rs2.getInt("SELLER_ID"));
               String name = String.valueOf(rs2.getString("SELLER_NAME"));
               String age = String.valueOf(rs2.getInt("AGE"));
               String num = String.valueOf(rs2.getString("PHONE_NUMBER"));
               String payment = String.valueOf(rs2.getInt("difference"));
               String tbData[] = {id,name,age,num,payment};
               DefaultTableModel model = (DefaultTableModel)jTable3.getModel(); 
                model.addRow(tbData);

            }con.close();
 }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        Welcome ob=new Welcome();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments        
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoreDetails_sub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoreDetails_sub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoreDetails_sub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoreDetails_sub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StoreDetails_sub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A1;
    private javax.swing.JRadioButton A2;
    private javax.swing.JRadioButton A3;
    private javax.swing.JRadioButton A4;
    private javax.swing.JRadioButton A5;
    private javax.swing.JRadioButton B1;
    private javax.swing.JRadioButton B10;
    private javax.swing.JRadioButton B11;
    private javax.swing.JRadioButton B2;
    private javax.swing.JRadioButton B3;
    private javax.swing.JRadioButton B4;
    private javax.swing.JRadioButton B5;
    private javax.swing.JRadioButton B6;
    private javax.swing.JRadioButton B7;
    private javax.swing.JRadioButton B8;
    private javax.swing.JRadioButton B9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
